name: ogg_caf_converter
version: 0.1.3
description: Converts OPUS audio files between OGG and CAF container formats using pure dart.
homepage: https://github.com/jt274/ogg_caf_converter
repository: https://github.com/jt274/ogg_caf_converter
issue_tracker: https://github.com/jt274/ogg_caf_converter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  android:
  ios:

topics:
  - audio
  - encoder
  - codec
  - converter
  - opus

dependencies:
  meta: ^1.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.14

funding:
  - https://www.paypal.com/ncp/payment/HFAXZ7CTFQC6L